import * as cheerio from "cheerio";
import type { AnyNode } from "domhandler";
import { looksLikePersonName } from "@/lib/util/names";
import { normalizeWhitespace } from "@/lib/util/text";

/**
 * DOM helpers shared by the HTML extractors.
 *
 * These do the unglamorous work of turning real university markup -- which is
 * inconsistent, decorative and frequently generated by a CMS -- into
 * something the extractors can reason about.
 */

export type Dom = cheerio.CheerioAPI;

export function loadHtml(html: string): Dom {
  return cheerio.load(html);
}

/** Strips the elements that never contain records but do contain names. */
export function stripChrome($: Dom): void {
  $("script, style, noscript, nav, header, footer, aside, form, svg").remove();
  $("[role=navigation], [role=banner], [role=contentinfo], .nav, .navbar, .menu, .footer, .header, .breadcrumb").remove();
}

export function textOf($: Dom, el: AnyNode | cheerio.Cheerio<AnyNode>): string {
  const node = "length" in el ? el : $(el);
  return normalizeWhitespace(node.text());
}

export function pageTitle($: Dom): string {
  return normalizeWhitespace($("title").first().text() || $("h1").first().text());
}

export function visibleText($: Dom, limit = 50_000): string {
  return normalizeWhitespace($("body").text()).slice(0, limit);
}

/**
 * Detects a page that renders its content with JavaScript.
 *
 * A page with a lot of script and almost no text is one we cannot honestly
 * claim to support with a static fetch. Recognising it lets the source be
 * marked as needing a different adapter, rather than silently yielding zero
 * records and looking like a parser bug.
 */
export function looksJavaScriptRendered($: Dom, rawHtml: string): boolean {
  const text = normalizeWhitespace($("body").text());
  const scriptBytes = $("script")
    .toArray()
    .reduce((sum, el) => sum + ($(el).html()?.length ?? 0), 0);

  if (text.length > 1200) return false;
  if (scriptBytes > 20_000 && text.length < 600) return true;
  if (rawHtml.length > 40_000 && text.length < 400) return true;
  return /<div[^>]+id=["'](root|app|__next)["']/i.test(rawHtml) && text.length < 800;
}

// --- Tables ----------------------------------------------------------------

export interface ParsedTable {
  headers: string[];
  rows: string[][];
  /** Per-row link hrefs, aligned to the row's cells. */
  rowLinks: Array<Array<string | undefined>>;
  element: AnyNode;
}

export function parseTables($: Dom, baseUrl: string): ParsedTable[] {
  const tables: ParsedTable[] = [];

  $("table").each((_, table) => {
    const $table = $(table);

    let headers: string[] = $table
      .find("thead th, thead td")
      .toArray()
      .map((th) => normalizeWhitespace($(th).text()).toLowerCase());

    const bodyRows = $table.find("tbody tr").toArray();
    const allRows = bodyRows.length > 0 ? bodyRows : $table.find("tr").toArray();

    // Some tables put headers in the first row instead of a thead.
    let dataRows = allRows;
    if (headers.length === 0 && allRows.length > 0) {
      const firstRow = $(allRows[0]!);
      const ths = firstRow.find("th");
      if (ths.length > 0) {
        headers = ths.toArray().map((th) => normalizeWhitespace($(th).text()).toLowerCase());
        dataRows = allRows.slice(1);
      }
    }

    const rows: string[][] = [];
    const rowLinks: Array<Array<string | undefined>> = [];

    for (const tr of dataRows) {
      const cells = $(tr).find("td, th").toArray();
      if (cells.length === 0) continue;
      rows.push(cells.map((td) => normalizeWhitespace($(td).text())));
      rowLinks.push(
        cells.map((td) => {
          const href = $(td).find("a[href]").first().attr("href");
          return href ? absoluteUrl(href, baseUrl) : undefined;
        }),
      );
    }

    if (rows.length > 0) tables.push({ headers, rows, rowLinks, element: table });
  });

  return tables;
}

/** Maps a table's headers onto the fields the pipeline understands. */
export const HEADER_ALIASES: Record<string, string[]> = {
  name: ["name", "student", "member", "player", "full name", "student name", "member name", "athlete", "officer"],
  firstName: ["first", "first name", "given name"],
  lastName: ["last", "last name", "surname", "family name"],
  role: ["role", "position", "title", "office", "officer", "pos", "pos."],
  organization: ["organization", "org", "chapter", "club", "team", "group", "society", "affiliation"],
  major: ["major", "program", "programme", "field of study", "discipline", "concentration"],
  year: ["year", "class", "cl", "cl.", "grad year", "graduation", "class year", "yr", "standing"],
  sport: ["sport", "team", "event", "discipline"],
  email: ["email", "e-mail", "contact", "email address"],
  hometown: ["hometown", "home town", "from"],
};

export function mapHeaders(headers: string[]): Record<number, string> {
  const map: Record<number, string> = {};
  headers.forEach((header, i) => {
    const clean = header.replace(/[^a-z\s.]/g, "").trim();
    for (const [field, aliases] of Object.entries(HEADER_ALIASES)) {
      if (aliases.includes(clean)) {
        // Do not let a later generic column overwrite a more specific match.
        if (!Object.values(map).includes(field)) map[i] = field;
        break;
      }
    }
  });
  return map;
}

/** Index of the column whose values most look like person names. */
export function guessNameColumn(rows: string[][]): number {
  const columnCount = Math.max(...rows.map((r) => r.length), 0);
  let bestIndex = -1;
  let bestHits = 0;

  for (let col = 0; col < columnCount; col++) {
    let hits = 0;
    for (const row of rows.slice(0, 40)) {
      const value = row[col];
      if (value && looksLikePersonName(value)) hits++;
    }
    if (hits > bestHits) {
      bestHits = hits;
      bestIndex = col;
    }
  }

  // Require the column to look like names in a clear majority of sampled rows.
  const sampled = Math.min(rows.length, 40);
  return bestHits >= Math.max(2, sampled * 0.4) ? bestIndex : -1;
}

// --- Repeated blocks -------------------------------------------------------

export interface RepeatedBlock {
  text: string;
  html: string;
  links: Array<{ text: string; href: string }>;
  /** Nearest preceding heading, which is usually the organization name. */
  heading?: string;
  /**
   * Text of the child elements most likely to hold the person's name, in
   * priority order. Card markup nearly always separates the name from the
   * detail line structurally, so reading the structure beats guessing where
   * to split the flattened text.
   */
  nameCandidates: string[];
  /** Everything in the block that is not the chosen name element. */
  remainder: string;
}

/**
 * Finds repeated sibling structures that each contain one person.
 *
 * Card grids and officer lists have no table to key off, so the heuristic is:
 * find parents with several similar children, and keep the groups whose
 * children mostly read as person names.
 */
export function findRepeatedBlocks($: Dom, baseUrl: string, minGroupSize = 3): RepeatedBlock[] {
  const candidates: RepeatedBlock[][] = [];

  $("ul, ol, div, section, tbody").each((_, parent) => {
    const $parent = $(parent);
    const children = $parent.children().toArray();
    if (children.length < minGroupSize) return;

    // Children must be structurally similar: same tag, similar class.
    const signature = (el: AnyNode) => {
      const $el = $(el);
      const tag = (el as { tagName?: string }).tagName ?? "";
      const cls = ($el.attr("class") ?? "").split(/\s+/).slice(0, 2).join(" ");
      return `${tag}.${cls}`;
    };

    const first = signature(children[0]!);
    const similar = children.filter((c) => signature(c) === first);
    if (similar.length < minGroupSize) return;

    const heading = findHeadingFor($, $parent);

    const blocks: RepeatedBlock[] = similar.map((el) => {
      const $el = $(el);
      const text = normalizeWhitespace($el.text());
      const { candidates, remainder } = nameCandidatesIn($, $el, text);

      return {
        text,
        html: $el.html() ?? "",
        links: $el
          .find("a[href]")
          .toArray()
          .map((a) => ({
            text: normalizeWhitespace($(a).text()),
            href: absoluteUrl($(a).attr("href") ?? "", baseUrl),
          }))
          .filter((l) => l.href.length > 0),
        heading,
        nameCandidates: candidates,
        remainder,
      };
    });

    const nameLike = blocks.filter((b) => containsPersonName(b.text)).length;
    if (nameLike >= Math.max(minGroupSize, blocks.length * 0.5)) {
      candidates.push(blocks);
    }
  });

  if (candidates.length === 0) return [];

  // Prefer the largest coherent group; nested matches would otherwise double
  // count the same people.
  candidates.sort((a, b) => b.length - a.length);
  const seen = new Set<string>();
  const out: RepeatedBlock[] = [];
  for (const group of candidates) {
    for (const block of group) {
      // Keyed by heading as well as text: one person listed under two
      // organizations is two memberships, not a duplicate.
      const key = `${block.heading ?? ""}::${block.text.slice(0, 160)}`;
      if (block.text.length < 3 || seen.has(key)) continue;
      seen.add(key);
      out.push(block);
    }
  }
  return out;
}

/**
 * Finds the sub-elements of a card that plausibly hold the person's name.
 *
 * Ordered by how strongly the markup signals a name: an explicit name class,
 * then a link or emphasis, then a heading, then the first child element.
 * Whatever is left over is returned as the remainder, which is where a role
 * or a published description usually lives.
 */
function nameCandidatesIn(
  $: Dom,
  $el: cheerio.Cheerio<AnyNode>,
  fullText: string,
): { candidates: string[]; remainder: string } {
  const selectors = [
    "[class*=name]",
    "a",
    "strong",
    "b",
    "h1, h2, h3, h4, h5, h6",
    "> span:first-child",
    "> div:first-child",
  ];

  const candidates: string[] = [];
  for (const selector of selectors) {
    const found = normalizeWhitespace($el.find(selector).first().text());
    if (found && found.length < 80 && !candidates.includes(found)) candidates.push(found);
  }

  const chosen = candidates[0];
  const remainder = chosen ? normalizeWhitespace(fullText.replace(chosen, " ")) : "";

  return { candidates, remainder };
}

function findHeadingFor($: Dom, $el: cheerio.Cheerio<AnyNode>): string | undefined {
  let node = $el;
  for (let i = 0; i < 4; i++) {
    const heading = node.prevAll("h1, h2, h3, h4, h5").first();
    if (heading.length > 0) {
      const text = normalizeWhitespace(heading.text());
      if (text) return text;
    }
    node = node.parent();
    if (node.length === 0) break;
  }
  return undefined;
}

/** True when any short line inside the text reads as a person's name. */
export function containsPersonName(text: string): boolean {
  const trimmed = normalizeWhitespace(text);
  if (looksLikePersonName(trimmed)) return true;

  // Cards usually read "Name<newline>Role", so test the leading fragment too.
  const firstFragment = trimmed.split(/[,–—|·•\n]/)[0] ?? "";
  return looksLikePersonName(firstFragment.trim());
}

export function absoluteUrl(href: string, baseUrl: string): string {
  try {
    return new URL(href, baseUrl).toString();
  } catch {
    return "";
  }
}

/** Extracts the first email address in a string, if any. */
export function findEmail(text: string): string | undefined {
  const match = text.match(/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/);
  return match?.[0]?.toLowerCase();
}

/** Extracts a four-digit graduation year, or a two-digit class year. */
export function findYear(text: string): string | undefined {
  const full = text.match(/\b(19|20)\d{2}\b/);
  if (full) return full[0];
  const short = text.match(/['’](\d{2})\b/);
  if (short?.[1]) {
    const n = Number.parseInt(short[1], 10);
    return String(n > 50 ? 1900 + n : 2000 + n);
  }
  return undefined;
}
